### ISSUE TITLE
Can't install Scrypt on Windows 10 with Ruby 2.3 64bit and DevKit 64bit

### ISSUE THREAD

**Issue by ThreeAxis** [pbhogan/scrypt#50]
When doing a `gem install Scrypt` I'm getting errors regarding the native compilation.

```
    C:\>gem install scrypt
    Temporarily enhancing PATH to include DevKit...
    Building native extensions.  This could take a while...
    ERROR:  Error installing scrypt:
            ERROR: Failed to build gem native extension.

        current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/scrypt-2.1.1/ext/scrypt
    C:/Ruby23/bin/ruby.exe -rubygems C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/scrypt-2.1.1 RUBYLIBDIR=C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/scrypt-2.1.1
    rake aborted!
    LoadError: cannot load such file -- ffi_c

    LoadError: cannot load such file -- ffi_c

    LoadError: cannot load such file -- 2.3/ffi_c

    LoadError: cannot load such file -- ffi-compiler/compile_task

    (See full trace by running task with --trace)

    rake failed, exit code 1

    Gem files will remain installed in C:/Ruby23/lib/ruby/gems/2.3.0/gems/scrypt-2.1.1 for inspection.
    Results logged to C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/scrypt-2.1.1/gem_make.out
```

Same happens when installing it using `gem install scrypt --platform=ruby`. It's the only gem that doesn't install. Tried to run it on 32bit Ruby and DevKit versions, but same problems happen. The Gem ffi does install neatly.

**Comment by stakach** [comment]
FFI must be pre-compiled.
The only way to solve the issue is:

1. Build the FFI gem manually on your platform and install the local copy
   * Clone the FFI github repo
   * `bundle install`
   * `rake gem:package`
   * `gem install ffi-1.x.x.gem`
2. Jump on the windows 10 insider preview fast ring and use the Linux emulation layer
   * http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
